---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-ip-stats-ui
  labels:
    version: {{.VERSION}}
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pttg-ip-stats-ui
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-ip-stats-ui
        version: {{.VERSION}}
    spec:
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.6
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        args:
          - --certs=/certs
          - --domain=pttg-ip-stats-ui.${KUBE_NAMESPACE}.svc.cluster.local
          - --expiry=8760h
          - --command=/usr/local/scripts/trigger_nginx_reload.sh
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy:v3.2.9
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '9000'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: HTTPS_REDIRECT
            value: 'FALSE'
          - name: SERVER_CERT
            value: /certs/tls.pem
          - name: SERVER_KEY
            value: /certs/tls-key.pem
          - name: ADD_NGINX_SERVER_CFG
            value: 'gzip off; location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
        ports:
          - name: https
            containerPort: 10443
      - name: keycloak-proxy
        image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v2.1.1
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        args:
          - --config=/etc/secrets/keycloak-api-stats-secret.yaml
          - --discovery-url=https://sso.digital.homeoffice.gov.uk/auth/realms/{{.KC_REALM}}
          - --client-id=pttg-ip-stats-{{.ENVIRONMENT}}
          - --listen=127.0.0.1:9000
          - --enable-logging=true
          - --enable-json-logging=true
          - --upstream-url=http://127.0.0.1:8000
          - --upstream-response-header-timeout=101s
          - --no-redirects=false
          - --redirection-url=https://{{.DOMAIN_NAME}}
          - --cors-origins='*'
          - --resources=uri=/healthz|white-listed=true
          - --resources=uri=/*|methods=GET,POST|roles=pttg-ip-stats
          - --secure-cookie=true
          - --http-only-cookie=true
          - --verbose
        ports:
          - name: keycloak-http
            containerPort: 9000
        volumeMounts:
          - name: keycloak-api-stats-secret
            mountPath: /etc/secrets
            readOnly: true
      - name: pttg-ip-stats-ui
        image: quay.io/ukhomeofficedigital/pttg-ip-stats-ui:{{.VERSION}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        env:
          - name: API_ROOT
            value: "https://pttg-ip-api.pttg-ip-{{.ENVIRONMENT}}.svc.cluster.local"
          - name: IP_API_AUTH
            valueFrom:
              secretKeyRef:
                name: pttg-ip-api-service-secrets
                key: pttg_ip_stats_ui
          - name: SERVER_PORT
            value: '8000'
        resources:
          limits:
            cpu: 1000m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
          - name: http
            containerPort: 8000
        livenessProbe:
          httpGet:
            path: /ping
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
        volumeMounts:
          - mountPath: /certs
            name: certs
            readOnly: true
      volumes:
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: keycloak-api-stats-secret
          secret:
            secretName: keycloak-api-stats-secret
        - name: bundle
          configMap:
            name: bundle
